// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: struct/struct_sc.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "struct/struct_sc.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace PKS {

namespace {

const ::google::protobuf::Descriptor* SC_HIGH_SCORE_LIST_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SC_HIGH_SCORE_LIST_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_struct_2fstruct_5fsc_2eproto() {
  protobuf_AddDesc_struct_2fstruct_5fsc_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "struct/struct_sc.proto");
  GOOGLE_CHECK(file != NULL);
  SC_HIGH_SCORE_LIST_descriptor_ = file->message_type(0);
  static const int SC_HIGH_SCORE_LIST_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SC_HIGH_SCORE_LIST, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SC_HIGH_SCORE_LIST, score_),
  };
  SC_HIGH_SCORE_LIST_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SC_HIGH_SCORE_LIST_descriptor_,
      SC_HIGH_SCORE_LIST::default_instance_,
      SC_HIGH_SCORE_LIST_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SC_HIGH_SCORE_LIST, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SC_HIGH_SCORE_LIST, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SC_HIGH_SCORE_LIST));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_struct_2fstruct_5fsc_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SC_HIGH_SCORE_LIST_descriptor_, &SC_HIGH_SCORE_LIST::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_struct_2fstruct_5fsc_2eproto() {
  delete SC_HIGH_SCORE_LIST::default_instance_;
  delete SC_HIGH_SCORE_LIST_reflection_;
}

void protobuf_AddDesc_struct_2fstruct_5fsc_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026struct/struct_sc.proto\022\003PKS\"1\n\022SC_HIGH"
    "_SCORE_LIST\022\014\n\004name\030\001 \003(\t\022\r\n\005score\030\002 \003(\005", 80);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "struct/struct_sc.proto", &protobuf_RegisterTypes);
  SC_HIGH_SCORE_LIST::default_instance_ = new SC_HIGH_SCORE_LIST();
  SC_HIGH_SCORE_LIST::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_struct_2fstruct_5fsc_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_struct_2fstruct_5fsc_2eproto {
  StaticDescriptorInitializer_struct_2fstruct_5fsc_2eproto() {
    protobuf_AddDesc_struct_2fstruct_5fsc_2eproto();
  }
} static_descriptor_initializer_struct_2fstruct_5fsc_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int SC_HIGH_SCORE_LIST::kNameFieldNumber;
const int SC_HIGH_SCORE_LIST::kScoreFieldNumber;
#endif  // !_MSC_VER

SC_HIGH_SCORE_LIST::SC_HIGH_SCORE_LIST()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PKS.SC_HIGH_SCORE_LIST)
}

void SC_HIGH_SCORE_LIST::InitAsDefaultInstance() {
}

SC_HIGH_SCORE_LIST::SC_HIGH_SCORE_LIST(const SC_HIGH_SCORE_LIST& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PKS.SC_HIGH_SCORE_LIST)
}

void SC_HIGH_SCORE_LIST::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SC_HIGH_SCORE_LIST::~SC_HIGH_SCORE_LIST() {
  // @@protoc_insertion_point(destructor:PKS.SC_HIGH_SCORE_LIST)
  SharedDtor();
}

void SC_HIGH_SCORE_LIST::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SC_HIGH_SCORE_LIST::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SC_HIGH_SCORE_LIST::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SC_HIGH_SCORE_LIST_descriptor_;
}

const SC_HIGH_SCORE_LIST& SC_HIGH_SCORE_LIST::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_struct_2fstruct_5fsc_2eproto();
  return *default_instance_;
}

SC_HIGH_SCORE_LIST* SC_HIGH_SCORE_LIST::default_instance_ = NULL;

SC_HIGH_SCORE_LIST* SC_HIGH_SCORE_LIST::New() const {
  return new SC_HIGH_SCORE_LIST;
}

void SC_HIGH_SCORE_LIST::Clear() {
  name_.Clear();
  score_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SC_HIGH_SCORE_LIST::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PKS.SC_HIGH_SCORE_LIST)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string name = 1;
      case 1: {
        if (tag == 10) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name(this->name_size() - 1).data(),
            this->name(this->name_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_name;
        if (input->ExpectTag(16)) goto parse_score;
        break;
      }

      // repeated int32 score = 2;
      case 2: {
        if (tag == 16) {
         parse_score:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 16, input, this->mutable_score())));
        } else if (tag == 18) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_score())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_score;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PKS.SC_HIGH_SCORE_LIST)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PKS.SC_HIGH_SCORE_LIST)
  return false;
#undef DO_
}

void SC_HIGH_SCORE_LIST::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PKS.SC_HIGH_SCORE_LIST)
  // repeated string name = 1;
  for (int i = 0; i < this->name_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
    this->name(i).data(), this->name(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE,
    "name");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(i), output);
  }

  // repeated int32 score = 2;
  for (int i = 0; i < this->score_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      2, this->score(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:PKS.SC_HIGH_SCORE_LIST)
}

::google::protobuf::uint8* SC_HIGH_SCORE_LIST::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PKS.SC_HIGH_SCORE_LIST)
  // repeated string name = 1;
  for (int i = 0; i < this->name_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name(i).data(), this->name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->name(i), target);
  }

  // repeated int32 score = 2;
  for (int i = 0; i < this->score_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(2, this->score(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PKS.SC_HIGH_SCORE_LIST)
  return target;
}

int SC_HIGH_SCORE_LIST::ByteSize() const {
  int total_size = 0;

  // repeated string name = 1;
  total_size += 1 * this->name_size();
  for (int i = 0; i < this->name_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->name(i));
  }

  // repeated int32 score = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->score_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->score(i));
    }
    total_size += 1 * this->score_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SC_HIGH_SCORE_LIST::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SC_HIGH_SCORE_LIST* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SC_HIGH_SCORE_LIST*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SC_HIGH_SCORE_LIST::MergeFrom(const SC_HIGH_SCORE_LIST& from) {
  GOOGLE_CHECK_NE(&from, this);
  name_.MergeFrom(from.name_);
  score_.MergeFrom(from.score_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SC_HIGH_SCORE_LIST::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SC_HIGH_SCORE_LIST::CopyFrom(const SC_HIGH_SCORE_LIST& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SC_HIGH_SCORE_LIST::IsInitialized() const {

  return true;
}

void SC_HIGH_SCORE_LIST::Swap(SC_HIGH_SCORE_LIST* other) {
  if (other != this) {
    name_.Swap(&other->name_);
    score_.Swap(&other->score_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SC_HIGH_SCORE_LIST::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SC_HIGH_SCORE_LIST_descriptor_;
  metadata.reflection = SC_HIGH_SCORE_LIST_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PKS

// @@protoc_insertion_point(global_scope)
