// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum/enum_sc.proto

#ifndef PROTOBUF_enum_2fenum_5fsc_2eproto__INCLUDED
#define PROTOBUF_enum_2fenum_5fsc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace PKENUM {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_enum_2fenum_5fsc_2eproto();
void protobuf_AssignDesc_enum_2fenum_5fsc_2eproto();
void protobuf_ShutdownFile_enum_2fenum_5fsc_2eproto();


enum SCPacketEnum {
  SC_BEGIN = 100,
  SC_HIGH_SCORE_LIST = 101,
  SC_END = 199
};
bool SCPacketEnum_IsValid(int value);
const SCPacketEnum SCPacketEnum_MIN = SC_BEGIN;
const SCPacketEnum SCPacketEnum_MAX = SC_END;
const int SCPacketEnum_ARRAYSIZE = SCPacketEnum_MAX + 1;

const ::google::protobuf::EnumDescriptor* SCPacketEnum_descriptor();
inline const ::std::string& SCPacketEnum_Name(SCPacketEnum value) {
  return ::google::protobuf::internal::NameOfEnum(
    SCPacketEnum_descriptor(), value);
}
inline bool SCPacketEnum_Parse(
    const ::std::string& name, SCPacketEnum* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SCPacketEnum>(
    SCPacketEnum_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace PKENUM

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::PKENUM::SCPacketEnum> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PKENUM::SCPacketEnum>() {
  return ::PKENUM::SCPacketEnum_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_enum_2fenum_5fsc_2eproto__INCLUDED
