// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum/enum_cs.proto

#ifndef PROTOBUF_enum_2fenum_5fcs_2eproto__INCLUDED
#define PROTOBUF_enum_2fenum_5fcs_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace PKENUM {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_enum_2fenum_5fcs_2eproto();
void protobuf_AssignDesc_enum_2fenum_5fcs_2eproto();
void protobuf_ShutdownFile_enum_2fenum_5fcs_2eproto();


enum CSPacketEnum {
  CS_BEGIN = 0,
  CS_HIGH_SCORE = 1,
  CS_END = 99
};
bool CSPacketEnum_IsValid(int value);
const CSPacketEnum CSPacketEnum_MIN = CS_BEGIN;
const CSPacketEnum CSPacketEnum_MAX = CS_END;
const int CSPacketEnum_ARRAYSIZE = CSPacketEnum_MAX + 1;

const ::google::protobuf::EnumDescriptor* CSPacketEnum_descriptor();
inline const ::std::string& CSPacketEnum_Name(CSPacketEnum value) {
  return ::google::protobuf::internal::NameOfEnum(
    CSPacketEnum_descriptor(), value);
}
inline bool CSPacketEnum_Parse(
    const ::std::string& name, CSPacketEnum* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CSPacketEnum>(
    CSPacketEnum_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace PKENUM

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::PKENUM::CSPacketEnum> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PKENUM::CSPacketEnum>() {
  return ::PKENUM::CSPacketEnum_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_enum_2fenum_5fcs_2eproto__INCLUDED
