// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum/enum_sc.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "enum/enum_sc.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace PKENUM {

namespace {

const ::google::protobuf::EnumDescriptor* SCPacketEnum_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_enum_2fenum_5fsc_2eproto() {
  protobuf_AddDesc_enum_2fenum_5fsc_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "enum/enum_sc.proto");
  GOOGLE_CHECK(file != NULL);
  SCPacketEnum_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_enum_2fenum_5fsc_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_enum_2fenum_5fsc_2eproto() {
}

void protobuf_AddDesc_enum_2fenum_5fsc_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022enum/enum_sc.proto\022\006PKENUM*A\n\014SCPacket"
    "Enum\022\014\n\010SC_BEGIN\020d\022\026\n\022SC_HIGH_SCORE_LIST"
    "\020e\022\013\n\006SC_END\020\307\001", 95);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "enum/enum_sc.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_enum_2fenum_5fsc_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_enum_2fenum_5fsc_2eproto {
  StaticDescriptorInitializer_enum_2fenum_5fsc_2eproto() {
    protobuf_AddDesc_enum_2fenum_5fsc_2eproto();
  }
} static_descriptor_initializer_enum_2fenum_5fsc_2eproto_;
const ::google::protobuf::EnumDescriptor* SCPacketEnum_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SCPacketEnum_descriptor_;
}
bool SCPacketEnum_IsValid(int value) {
  switch(value) {
    case 100:
    case 101:
    case 199:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PKENUM

// @@protoc_insertion_point(global_scope)
