//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: enum/enum_cs.proto
namespace PKENUM
{
    [global::ProtoBuf.ProtoContract(Name=@"CSPacketEnum")]
    public enum CSPacketEnum
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_BEGIN", Value=0)]
      CS_BEGIN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_HIGH_SCORE", Value=1)]
      CS_HIGH_SCORE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_END", Value=99)]
      CS_END = 99
    }
  
}
// Generated from: enum/enum_sc.proto
namespace PKENUM
{
    [global::ProtoBuf.ProtoContract(Name=@"SCPacketEnum")]
    public enum SCPacketEnum
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_BEGIN", Value=100)]
      SC_BEGIN = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_HIGH_SCORE_LIST", Value=101)]
      SC_HIGH_SCORE_LIST = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_END", Value=199)]
      SC_END = 199
    }
  
}
// Generated from: struct/struct_cs.proto
namespace PKS
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_HIGH_SCORE")]
  public partial class CS_HIGH_SCORE : global::ProtoBuf.IExtensible
  {
    public CS_HIGH_SCORE() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: struct/struct_sc.proto
namespace PKS
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_HIGH_SCORE_LIST")]
  public partial class SC_HIGH_SCORE_LIST : global::ProtoBuf.IExtensible
  {
    public SC_HIGH_SCORE_LIST() {}
    
    private readonly global::System.Collections.Generic.List<string> _name = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> name
    {
      get { return _name; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _score = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> score
    {
      get { return _score; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: etc/struct_etc.proto
namespace PKS
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vec2")]
  public partial class Vec2 : global::ProtoBuf.IExtensible
  {
    public Vec2() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vec3")]
  public partial class Vec3 : global::ProtoBuf.IExtensible
  {
    public Vec3() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FieldObjectBasicInfo")]
  public partial class FieldObjectBasicInfo : global::ProtoBuf.IExtensible
  {
    public FieldObjectBasicInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private PKS.Vec2 _pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PKS.Vec2 pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}